# Generated by Django 5.2.3 on 2025-06-19 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название комнаты')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль (хешированный)')),
                ('max_users', models.PositiveIntegerField(default=10, verbose_name='Макс. участников')),
                ('encryption_algorithm', models.CharField(choices=[('magma', 'Магма (ГОСТ Р 34.12-2015)'), ('kuznechik', 'Кузнечик (ГОСТ Р 34.12-2015)')], default='kuznechik', max_length=20, verbose_name='Алгоритм шифрования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('encryption_key', models.CharField(blank=True, max_length=256)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
