# Generated by Django 5.2.3 on 2025-06-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='moderator_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='moderator_username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
